# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vger < Formula
  desc "V'Ger — AI-powered conference video knowledge assimilation system"
  homepage "https://github.com/costap/vger"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/costap/vger/releases/download/v0.1.0/vger_darwin_amd64.tar.gz"
      sha256 "bcdd278bcd70013dfcdae176ba59f563711d23b877d87907f82edc4ac6e6aa0d"

      define_method(:install) do
        bin.install "vger"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/costap/vger/releases/download/v0.1.0/vger_darwin_arm64.tar.gz"
      sha256 "e3b760dbefea478376a50cd2d2475736153fb1079d0085f5f24bc9f0a3375e33"

      define_method(:install) do
        bin.install "vger"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/costap/vger/releases/download/v0.1.0/vger_linux_amd64.tar.gz"
      sha256 "b9ececbbc6034b8c2f79496ad955c07677d1ea387efb9e295337862de741d862"
      define_method(:install) do
        bin.install "vger"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/costap/vger/releases/download/v0.1.0/vger_linux_arm64.tar.gz"
      sha256 "b3299b7c477dc51f4aaec587a8b31d2e4eecce6e94b89c94121e267b343d40ef"
      define_method(:install) do
        bin.install "vger"
      end
    end
  end

  test do
    system "#{bin}/vger", "--help"
  end
end
