# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vger < Formula
  desc "V'Ger — AI-powered conference video knowledge assimilation system"
  homepage "https://github.com/costap/vger"
  version "0.8.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/costap/vger/releases/download/v0.8.4/vger_darwin_amd64.tar.gz"
      sha256 "6abe69a52afac02c803d1502ab0a6d2f239db8021d3183bc3912ef330872dd02"

      define_method(:install) do
        bin.install "vger"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/costap/vger/releases/download/v0.8.4/vger_darwin_arm64.tar.gz"
      sha256 "2c324ffb227cb1c63183ee96d4ab2d0b6b992380e02e71a61af3ce800ceba5b1"

      define_method(:install) do
        bin.install "vger"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/costap/vger/releases/download/v0.8.4/vger_linux_amd64.tar.gz"
      sha256 "7efe4dc430be505277cf79eed2c9cf5cc1e14b6f7b7f3304af8c141c41c76201"
      define_method(:install) do
        bin.install "vger"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/costap/vger/releases/download/v0.8.4/vger_linux_arm64.tar.gz"
      sha256 "b2d36c175731d43e684b94638f839d54e888c4a99c8ccda2c4b3989e5e8f7f5e"
      define_method(:install) do
        bin.install "vger"
      end
    end
  end

  test do
    system "#{bin}/vger", "--help"
  end
end
