# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vger < Formula
  desc "V'Ger — AI-powered conference video knowledge assimilation system"
  homepage "https://github.com/costap/vger"
  version "0.8.10"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/costap/vger/releases/download/v0.8.10/vger_darwin_amd64.tar.gz"
      sha256 "bb705b389e5b6dbde4100718a4fcbede066ef898c7f5f7a3f4d69b540a5a90a7"

      define_method(:install) do
        bin.install "vger"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/costap/vger/releases/download/v0.8.10/vger_darwin_arm64.tar.gz"
      sha256 "5f5a1734723bd3e9e840bd5b92aefc78906d824bbbe518320255e5bcc11b9bbb"

      define_method(:install) do
        bin.install "vger"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/costap/vger/releases/download/v0.8.10/vger_linux_amd64.tar.gz"
      sha256 "9c9a5e5b2c9971317bcfc65916619b4cef4f6c71e7f3e0be7389099b8e8b9df0"
      define_method(:install) do
        bin.install "vger"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/costap/vger/releases/download/v0.8.10/vger_linux_arm64.tar.gz"
      sha256 "90df34ef80b194ac3a7d87bb73e973cea0548cd3f95577be4df206ba098eb906"
      define_method(:install) do
        bin.install "vger"
      end
    end
  end

  test do
    system "#{bin}/vger", "--help"
  end
end
